# Generated by Django 2.2.13 on 2020-10-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=1000)),
                ('sort_rank', models.IntegerField(default=100)),
                ('location', models.CharField(blank=True, max_length=1000)),
                ('time_start', models.DateField(blank=True)),
                ('time_end', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
