# Generated by Django 2.2.13 on 2020-10-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0002_experience_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='nature',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
