# Generated by Django 2.2.13 on 2020-10-24 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000)),
                ('record_type', models.CharField(blank=True, max_length=1000)),
                ('reference', models.CharField(blank=True, max_length=1000)),
                ('status', models.CharField(blank=True, max_length=1000)),
                ('action', models.CharField(blank=True, max_length=1000)),
                ('content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
