# Generated by Django 2.2.13 on 2020-09-14 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_auto_20200913_2152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolios',
            options={'verbose_name': 'Portfolio', 'verbose_name_plural': 'Portfolios'},
        ),
    ]
