# Generated by Django 2.2.13 on 2020-09-18 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0003_auto_20200915_1043'),
        ('portfolios', '0003_auto_20200914_2106'),
    ]

    operations = [
    ]
