# Generated by Django 2.2.13 on 2020-10-06 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0003_auto_20200913_2255'),
        ('portfolios', '0004_merge_20200918_0449'),
    ]

    operations = [
    ]
