# Generated by Django 2.2.13 on 2020-10-10 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0005_auto_20201010_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolios',
            name='project_hours',
            field=models.IntegerField(blank=True, default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portfolios',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='portfolios',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
