# Generated by Django 2.2.13 on 2020-10-10 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0006_auto_20201010_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolios',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='portfolios',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
