# Generated by Django 2.2.13 on 2020-10-10 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0008_auto_20201010_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolios',
            name='project_enddate',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='portfolios',
            name='project_startdate',
            field=models.DateTimeField(blank=True),
        ),
    ]
