# Generated by Django 2.2.13 on 2020-10-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0010_auto_20201011_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolios',
            name='contact_email',
            field=models.EmailField(default='leeyuhan@qq.com', max_length=254),
            preserve_default=False,
        ),
    ]
