# Generated by Django 2.2.13 on 2020-10-11 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0005_merge_20201006_0408'),
        ('portfolios', '0010_auto_20201011_0000'),
    ]

    operations = [
    ]
