# Generated by Django 2.2.13 on 2020-10-11 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0011_portfolios_contact_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolios',
            name='contact_email',
        ),
    ]
