# Generated by Django 2.2.13 on 2020-10-11 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0012_remove_portfolios_contact_email'),
        ('portfolios', '0011_merge_20201011_0030'),
    ]

    operations = [
    ]
