# Generated by Django 2.2.13 on 2020-10-17 10:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0012_remove_portfolios_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolios',
            name='styled_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
