# Generated by Django 2.2.13 on 2020-10-18 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0013_portfolios_styled_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolios',
            name='sort_rank',
            field=models.IntegerField(default=100),
        ),
    ]
