# Generated by Django 2.2.13 on 2020-10-18 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0013_merge_20201011_2221'),
        ('portfolios', '0013_portfolios_styled_description'),
    ]

    operations = [
    ]
