# Generated by Django 2.2.13 on 2020-10-18 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0015_portfolios_active'),
        ('portfolios', '0014_merge_20201018_0302'),
    ]

    operations = [
    ]
