# Generated by Django 2.2.13 on 2020-10-11 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webPages', '0002_experiences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiences',
            name='webPages',
        ),
        migrations.AddField(
            model_name='experiences',
            name='webPagesId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='webPages.WebPages'),
            preserve_default=False,
        ),
    ]
