# Generated by Django 2.2.13 on 2020-10-11 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webPages', '0003_auto_20201011_0251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webpages',
            old_name='youtube',
            new_name='git',
        ),
    ]
