# Generated by Django 2.2.13 on 2020-10-11 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webPages', '0005_portfolio_back_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpages',
            name='contact_email',
            field=models.EmailField(default='leeyuhan@qq.com', max_length=254),
            preserve_default=False,
        ),
    ]
